### ISSUE TITLE
Alternative to 'import * as' module syntax

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [CharlesStover/fetch-suspense#11]
This will soon no longer be considered valid JavaScript:

```javascript
import * as useFetch from 'fetch-suspense'

useFetch(/*...*/)
```

https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this/39415662#39415662

> An ES6 module namespace object cannot be invoked as a function or with new.
> The thing you import using * as X from a module is defined to only have properties.

As a backwards-compatible change, this module should have something like this added to the bottom of `fetch-suspense.ts`:

`module.exports.useFetch = module.exports`

That way we'll be able to do this:

```javascript
import { useFetch } from 'fetch-suspense'

useFetch(/*...*/)
```

**Comment by quisido** [comment]
The current implementation does not use `import *`. If you are not using esInterop/syntheticDefaultImports, you need to do `import useFetch = require('fetch-suspense')`.

I would like to have this fixed when the `.d.ts` is fixed, though, with `module.exports.default = module.exports` as opposed to `import { useFetch }`.

Let me know if `import useFetch =` syntax fixes your issue, as I currently believe this issue should be closed and is solved by that correction.

**Comment by JoshuaKGoldberg** [comment]
> Let me know if import useFetch = syntax fixes your issue

It does not, sadly. That syntax is TypeScript-specific so best practice is to avoid it.

To be clear: `import * as m` syntax isn't just a TypeScript thing; it's also how ES modules are intended to work. `import m =` is just TypeScript. [MDN reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

**Comment by quisido** [comment]
Given your issue about the `.d.ts` file, I was under the impression you were using TypeScript.

The desired output, imo, is:

```JavaScript
// TypeScript and ES6 modules:
import useFetch from 'fetch-suspense';

// CommonJS in SSR applications:
const useFetch = require('fetch-suspense');
```

I don't think there is any system that would not support a default export and instead rely on `import * as useFetch`. Correct me if I'm wrong.
