### ISSUE TITLE
TypeScript 3.6.2 removed GlobalFetch

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [CharlesStover/fetch-suspense#23]
Similar issue: https://github.com/apollographql/apollo-link/issues/1131

Wamp wump. I can fix this too. 😅

**Comment by JoshuaKGoldberg** [comment]
Ping @CharlesStover - any chance we could get this in soon please? It's blocking a few repositories I work in from updating to TypeScript 3.7 for `?.` and `??` operators 😊

**Comment by quisido** [comment]
Thanks, I didn't get a notification from the PR update. It's been merged. I'll bump the patch version now so it'll hit NPM soon.

**Comment by JoshuaKGoldberg** [comment]
Psst @CharlesStover - did the publish go through? https://www.npmjs.com/package/fetch-suspense doesn't show an update.

**Comment by quisido** [comment]
Thanks for the heads up. Looks like a space found its way into the version. It's fixed and should be deployed soon.
