### ISSUE TITLE
UseFetch factory for creating the hook with a custom fetch implementation.

### ISSUE THREAD

**Issue by quisido** [CharlesStover/fetch-suspense#8]
```JavaScript
export const createUseFetch = fetch => {/*...*/};
export default createUseFetch(global.fetch);
```

**Comment by tomchentw** [comment]
@CharlesStover I've implemented this in the PR on my fork-ed repo:
https://github.com/tomchentw/fetch-suspense/pull/1/files

Previously I wasn't sure about using ES2015 export syntax and thus doesn't create this PR here. Let me know what you think.

**Comment by tomchentw** [comment]
I do have another issue of having different JSON content-type: `application/vnd.api+json`

https://github.com/CharlesStover/fetch-suspense/blob/903f9601a8e3a3e711ac58703c357cc89d24a09e/fetch-suspense.ts#L47

**Comment by quisido** [comment]
The way I'm handling the ES2015 exports alongside CommonJS exports now is to do this:

```JavaScript
function CommonJSExport() {
}
CommonJSExport.default = CommonJSExport;
module.exports = CommonJSExport; // commonjs export
```

You should be able to just tack on any additional exports as a property of `CommonJSExport`.

```JavaScript
const createUseFetch = () => { };
const useFetch = createUseFetch(global.fetch);
useFetch.createUseFetch = createUseFetch;
useFetch.default = useFetch;
module.exports = useFetch;
```

Let me know if you have trouble with it.

I'm definitely okay with adding:
```JavaScript
const jsonContentTypes = new Set([ 'application/json', 'application/vnd.api+json' ]);
/* ... */
jsonContentTypes.has(contentType)
```

It would be nice to support custom JSON headers in case users have other obscure headers for JSON. Maybe as a part of the factory in the future. For now, two is fine for a quick fix.
